let
    Origen = #"NIR BATTILNA",

    // Detectores de formato
    #"Con Table006" = Table.SelectRows(Origen, each [Contenido.Name] = "Table006 (Page 2)"),
    #"Archivos con Table006" = List.Distinct(#"Con Table006"[Name]),

    #"Con Table005 Page2" = Table.SelectRows(Origen, each [Contenido.Name] = "Table005 (Page 2)"),
    #"Archivos con Table005 Page2" = List.Distinct(#"Con Table005 Page2"[Name]),

    // 4 tablas: solo Table004 y no tiene Table005 ni Table006
    #"Table004 solo 4 tablas" = Table.SelectRows(
        Origen,
        each [Contenido.Name] = "Table004 (Page 2)"
            and not List.Contains(#"Archivos con Table005 Page2", [Name])
            and not List.Contains(#"Archivos con Table006", [Name])
    ),

    // 5 tablas: Table004 + Table005
    #"Table004 solo 5 tablas" = Table.SelectRows(
        Origen,
        each [Contenido.Name] = "Table004 (Page 2)"
            and List.Contains(#"Archivos con Table005 Page2", [Name])
            and not List.Contains(#"Archivos con Table006", [Name])
    ),

    #"Table005 solo 5 tablas" = Table.SelectRows(
        Origen,
        each [Contenido.Name] = "Table005 (Page 2)"
            and not List.Contains(#"Archivos con Table006", [Name])
    ),

    // 6 y 7 tablas
    #"Table006 solo 6y7 tablas" = Table.SelectRows(
        Origen,
        each [Contenido.Name] = "Table006 (Page 2)"
    ),

    #"Table007 solo 7 tablas" = Table.SelectRows(
        Origen,
        each [Contenido.Name] = "Table007 (Page 2)"
    ),

    #"Tablas unidas" = Table.Combine({
        #"Table004 solo 4 tablas",
        #"Table004 solo 5 tablas",
        #"Table005 solo 5 tablas",
        #"Table006 solo 6y7 tablas",
        #"Table007 solo 7 tablas"
    }),

    #"Se expandió Contenido.Data" = Table.ExpandTableColumn(
        #"Tablas unidas",
        "Contenido.Data",
        {"Column1", "Column2", "Column3", "Column4", "Column5"},
        {"Parametro", "Valor_Humedo", "Unidad_Humedo", "Valor_MS", "Unidad_MS"}
    ),

    #"Columnas conservadas" = Table.SelectColumns(
        #"Se expandió Contenido.Data",
        {"Name", "Contenido.Name", "Parametro", "Valor_Humedo", "Unidad_Humedo", "Valor_MS", "Unidad_MS"}
    ),

    #"Seccion agregada" = Table.AddColumn(
        #"Columnas conservadas",
        "Seccion",
        each if [Parametro] = null and [Valor_Humedo] <> null then [Valor_Humedo] else null
    ),

    #"Agrupado por Name y Tabla" = Table.Group(
        #"Seccion agregada",
        {"Name", "Contenido.Name"},
        {{"Datos", each Table.FillDown(_, {"Seccion"}), type table}}
    ),

    #"Se expandió Datos" = Table.ExpandTableColumn(
        #"Agrupado por Name y Tabla",
        "Datos",
        {"Parametro", "Valor_Humedo", "Unidad_Humedo", "Valor_MS", "Unidad_MS", "Seccion"},
        {"Parametro", "Valor_Humedo", "Unidad_Humedo", "Valor_MS", "Unidad_MS", "Seccion"}
    ),

    #"Seccion corregida" = Table.AddColumn(
        #"Se expandió Datos",
        "Seccion_Final",
        each
            if [Seccion] <> null then [Seccion]
            else if [Contenido.Name] = "Table005 (Page 2)" or [Contenido.Name] = "Table007 (Page 2)" then "Valores energéticos"
            else "Perfil de fermentación"
    ),

    #"Columnas quitadas1" = Table.RemoveColumns(#"Seccion corregida", {"Seccion"}),
    #"Seccion renombrada" = Table.RenameColumns(#"Columnas quitadas1", {{"Seccion_Final", "Seccion"}}),

    #"Filas filtradas" = Table.SelectRows(
        #"Seccion renombrada",
        each [Parametro] <> null and [Parametro] <> ""
    ),

    #"Valor reemplazado" = Table.ReplaceValue(
        #"Filas filtradas",
        ".",
        ",",
        Replacer.ReplaceText,
        {"Valor_Humedo", "Valor_MS"}
    ),

    #"Valor reemplazado1" = Table.ReplaceValue(
        #"Valor reemplazado",
        "-",
        null,
        Replacer.ReplaceValue,
        {"Valor_Humedo", "Valor_MS"}
    ),

    #"Tipo cambiado" = Table.TransformColumnTypes(
        #"Valor reemplazado1",
        {{"Valor_MS", type number}, {"Valor_Humedo", type number}}
    ),

    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado", {"Contenido.Name"})
in
    #"Columnas quitadas"
