let
    Origen = Folder.Files("C:\Users\JOSE\Downloads\NIR BATTILNA"),

    ConContenido = Table.AddColumn(Origen, "Contenido", each Pdf.Tables([Content])),

    Expandido = Table.ExpandTableColumn(
        ConContenido,
        "Contenido",
        {"Name", "Kind", "Data"},
        {"Contenido.Name", "Contenido.Kind", "Contenido.Data"}
    ),

    SoloPage001 = Table.SelectRows(
        Expandido,
        each [Contenido.Kind] = "Page" and [Contenido.Name] = "Page001"
    ),

    DataNormalizada = Table.TransformColumns(
        SoloPage001,
        {
            {
                "Contenido.Data",
                each
                    let
                        t0 = _,
                        cols = Table.ColumnNames(t0),
                        t1 = if List.Contains(cols, "Column3") then t0 else Table.AddColumn(t0, "Column3", each null),
                        t2 = if List.Contains(Table.ColumnNames(t1), "Column4") then t1 else Table.AddColumn(t1, "Column4", each null),
                        t3 = Table.SelectColumns(t2, {"Column3", "Column4"})
                    in
                        t3
            }
        }
    ),

    Expandido2 = Table.ExpandTableColumn(
        DataNormalizada,
        "Contenido.Data",
        {"Column3", "Column4"},
        {"Campo", "Valor"}
    ),

    FilasMetadatos = Table.SelectRows(
        Expandido2,
        each List.Contains(
            {
                "Fecha y hora:",
                "Empresa:",
                "Lote:",
                "Muestra:",
                "Producto:",
                "Adquisición:",
                "Instrumento:",
                "Notas:"
            },
            [Campo]
        )
    ),

    Conservadas = Table.SelectColumns(
        FilasMetadatos,
        {"Name", "Campo", "Valor"}
    ),

    FilasValidas = Table.SelectRows(
        Conservadas,
        each [Valor] <> null and Text.Trim(Text.From([Valor])) <> ""
    ),

    Agrupado = Table.Group(
        FilasValidas,
        {"Name", "Campo"},
        {{"Valor", each List.First(List.RemoveNulls([Valor])), type text}}
    ),

    Dinamizada = Table.Pivot(
        Agrupado,
        List.Distinct(Agrupado[Campo]),
        "Campo",
        "Valor"
    ),

    TipoCambiado = Table.TransformColumnTypes(
        Dinamizada,
        {{"Fecha y hora:", type datetime}}
    )
in
    TipoCambiado
